reference_genome:
  /nfs/BigData01/Big_Data/Genomes/Lolium_perenne/clean_genome_lolium.fna.gz
#  /nfs/BigData01/Big_Data/Genomes/Rubus_Occidentalis/BWA_index/Rubus_occidentalis_v1.0.a1.scaffolds.fasta.gz
#  /nfs/BigData01/Big_Data/Genomes/Cucumis_sativus/cucumber_ChineseLong_v2_genome.fa
output_dir:
  /nfs/BigData01/Big_Data/Lolium/results/grassen_freebayes/
#  /nfs/BigData01/Big_Data/L15-217_framboos/results/koen/framboos_freebayes/
basename:
  grassen_freebayes # how your data is called, plz do not use a extension here.
input_dir:
  /nfs/data/Big_Data/Lolium/raw_sequences
pair_file:
#  /home/koenvd/SNP_selection/framboos_pairs_names.txt
  /home/koenvd/SNP_selection/grassen_pairs.txt
variant_caller:
#  samtools
  freebayes
method:
  frequency
#  snps
vcf_filter:
  -q: 20
  -d: 30
  -s: 4
  -r: 0.8
configure_snp_set:
  genetic_distance: 5
flanking_sequences:
  -l: 100
  -m: 0.2
  -p: 0.5