reference_genome:
#  /nfs/BigData01/Big_Data/Genomes/Rubus_Occidentalis/BWA_index/Rubus_occidentalis_v1.0.a1.scaffolds.fasta.gz
  /nfs/BigData01/Big_Data/Genomes/Lolium_perenne/GCA_001735685.1_ASM173568v1_genomic.fna.gz
  #  /nfs/BigData01/Big_Data/Genomes/Cucumis_sativus/cucumber_ChineseLong_v2_genome.fa
output_dir:
  /nfs/BigData01/Big_Data/Lolium/results/grassen_pool/
basename:
  grassen_pool # how your data is called, plz do not use a extension here.
merge_files:
  input_dir: /nfs/BigData01/Big_Data/Lolium/raw_pools/
variant_caller:
  samtools

